name: VirtualTag
version: @VERSION@
main: me.rerere.virtualtag.VirtualTag
author: RE
depend:
  - packetevents
softdepend:
  - PlaceholderAPI
commands:
  virtualtag:
    aliases:
      - vt
      - vtag
    usage: /virtualtag <param>
    description: The main command of VirtualTag

permissions:
  virtualtag.*:
    description: The parent permission of VirtualTag
    default: op
    children:
      virtualtag.reload: true
      virtualtag.groups: true
  virtualtag.reload:
    default: op
  virtualtag.groups:
    default: op